build:
  stage: build
  image: python:latest
  script:
    - python --version
    - pip --version
    - pip install pytest
    - pytest --version
    - echo "Build Environment"
test:
  stage: test
  image: $CI_REGISTRY_IMAGE
  rules:
   - if: $CI_REGISTRY_IMAGE == "schedule"
  script:
    - pip install coverage
    - coverage run -m unittest coverageUnittest.py
    - coverage report

deploy:
  stage: build
  image: docker
  services:
   - docker:dind
  rules:
   - if: $CI_REGISTRY_IMAGE == "schedule"
  script:
   - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGITRY --password-stdin
   - docker build -t $CI_REGISTRY_IMAGE .
   - docker push $CI_REGISTRY_IMAGE

