build
stages:
  - build
  - test

build:
  stage: build
  image: mtommyp14/bmi:v1
  

test:
  script:
    - pip install coverage
    - coverage run -m unittest coverageUnittest.py
    - coverage report 
