build_env:
  image: python:latest
  script:
    - python --version
    - pip --version
    - pip install pytest
    - pytest --version
    - echo "Build Environment"

run_test:
  stage: test
  image: $CI_REGISTRY_IMAGE
  script:
    - pip install coverage
    - coverage run -m unittest coverageUnittest.py
    - coverage report

build_image:
  stage: build
  image: docker:dind
  services:
   - docker:dind
  script:
   - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
   - docker build -t $CI_REGISTRY_IMAGE .
   - docker push $CI_REGISTRY_IMAGE

